services:
  - type: web
    name: Automated-Email-Responder
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TRANSFORMERS_CACHE
        value: /tmp/transformers
